Repository opensearch-project/project-website, pull requests merged in 2023-08, with the labels that each got.

#1841 Update peterzhuamazon (zhujiaxiang) author information on opensearch.org
  _authors/zhujiaxiang.markdown
Labels: enhancement

#1801 Fix EOL date
  releases.md
Labels: awaiting-response

#1804 New blog alerting and anomaly detection visualizations
  _authors/vagimeli.markdown
  _posts/2023-07-27-alert-anomaly-visual.md
  assets/media/blog-images/2023-07-20-alert-anomaly-visual.md/add-detector.jpg
  assets/media/blog-images/2023-07-20-alert-anomaly-visual.md/add-monitor.png
  assets/media/blog-images/2023-07-20-alert-anomaly-visual.md/alerting-options-context-menu.png
  assets/media/blog-images/2023-07-20-alert-anomaly-visual.md/anomaly-options-context-menu.jpg
  assets/media/blog-images/2023-07-20-alert-anomaly-visual.md/dashboard-options-context-menu.png
  assets/media/blog-images/2023-07-20-alert-anomaly-visual.md/events-flyout.png
  assets/media/blog-images/2023-07-20-alert-anomaly-visual.md/save-associated-detector.jpg
  assets/media/blog-images/2023-07-20-alert-anomaly-visual.md/save-associated-monitor.png
  assets/media/blog-images/2023-07-20-alert-anomaly-visual.md/save-new-detector.jpg
  assets/media/blog-images/2023-07-20-alert-anomaly-visual.md/save-new-monitor.png
  assets/media/blog-images/2023-07-20-alert-anomaly-visual.md/view-events-context-menu.png
Labels: awaiting-response

#1902 OpenSearchCon 2023 Speaker Jiaxiang (Peter) Zhu information corrections
  _speaker_sessions/sgaikawad_session.md
  _speakers/pzhu.md
  assets/media/opensearchcon/speakers/jzhu.jpg
Labels: documentation

#1916 Partner highlight for SageMaker, Haystack, and OpenSearch
  _authors/tuanacelik.markdown
  _posts/2023-08-25-sagemaker-haystack-opensearch.markdown
  assets/media/authors/tuanacelik.jpg
  assets/media/blog-images/2023-08-25-sagemaker-haystack-opensearch/Architecture.png
Labels: new blog, approved-blog
