Repository opensearch-project/project-website, pull requests merged in 2024-05, with the labels that each got.

#2833 Update 2024 OpenSearch Project Public PGP Key Renewal Changelog
  verify-signatures.markdown
Labels: enhancement

#2849 Merge Update 2024 OpenSearch Project Public PGP Key Renewal Changelog to prod branch
  verify-signatures.markdown
Labels: documentation

#2913 Announcing OpenSearchCon North America 2024 Blog
  _posts/2024-06-01-opensearchcon-north-america-2024-registration-and-cfp.md
Labels: approved-blog
