Repository opensearch-project/project-website, pull requests merged in 2024-08, with the labels that each got.

#3146 [Blog] Initial a blog: a neural sparse two-phase algorithm.
  _community_members/congguan.md
  _posts/2024-08-07-Introducing-a-neural-sparse-two-phase-algorithm.md
  assets/media/blog-images/2024-08-07-Introducing-a-neural-sparse-two-phase-algorithm/two-phase-bi-encoder-p99-latency.jpg
  assets/media/blog-images/2024-08-07-Introducing-a-neural-sparse-two-phase-algorithm/two-phase-doc-model-p99-latency.jpg
  assets/media/community/members/congguan.jpg
Labels: new blog, awaiting-response

#3091 Initial blog PR: "Using heuristic evaluation to inform the user exper…
  _community_members/rsalas.md
  _posts/2024-07-19-using-heuristic-evaluation-to-inform-the-user-experience-strategy-of-a-product.markdown
  assets/media/blog-images/2024-07-19-using-heuristic-evaluation-to-inform-the-user-experience-strategy-of-a-product/Image.jpg
  assets/media/blog-images/2024-07-19-using-heuristic-evaluation-to-inform-the-user-experience-strategy-of-a-product/Image1.jpg
  assets/media/blog-images/2024-07-19-using-heuristic-evaluation-to-inform-the-user-experience-strategy-of-a-product/Image2.jpg
Labels: ready to publish

#3241 Update releases page from Feb to Aug 2024
  releases.md
Labels: documentation
