Repository opensearch-project/project-website, pull requests merged in 2024-04, with the labels that each got.

#2700 Add encoding check workflow to ensure all the files having utf-8 encoding and value continue-on-error
  .github/workflows/encoding-check.yml
  .github/workflows/vale.yml
Labels: enhancement, workflows

#2698 [Blogpost] Configurable Automation for OpenSearch ML Use Cases
  _community_members/amitgalitz.md
  _community_members/hnyng.md
  _community_members/jpalis.md
  _community_members/ohltyler.md
  _posts/2024-04-05-Configurable-Automation-for-OpenSearch-ML-Use-Cases.md
  assets/media/community/members/jpalis.jpg
Labels: new blog, blog-under-review

#2670 Adds new community project
  _community_projects/gekatateam-neptunus.markdown
Labels: awaiting-response

#2661 Adding blog post for Multimodal semantic search
  _community_members/haoyng.md
  _posts/2024-04-11-multimodal-semantic-search.md
  assets/media/blog-images/2024-03-14-multimodal-semantic-search/search-image-only-visual-results.png
  assets/media/blog-images/2024-03-14-multimodal-semantic-search/search-text-and-image-visual-results.png
  assets/media/blog-images/2024-03-14-multimodal-semantic-search/search-text-only-visual-results.png
  assets/media/blog-images/2024-03-14-multimodal-semantic-search/semantic-space-distances.png
  assets/media/blog-images/2024-03-14-multimodal-semantic-search/titan-multimodal-embeddings-architecture.png
  assets/media/community/members/haoyng.jpg
Labels: awaiting-response
